---
apiVersion: v1
kind: Pod
metadata:
  name: zookeeper
  labels:
    name: zookeeper
spec:
  containers:
  - name: zookeeper
    image: docker.io/bitnami/zookeeper:latest
    ports:
    - containerPort: 2181
    env:
    - name: ALLOW_ANONYMOUS_LOGIN
      value: "yes"
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka
  labels:
    name: kafka
spec:
  containers:
  - name: kafka
    image: docker.io/wurstmeister/kafka:2.11-2.0.0
    ports:
    - name: primary
      containerPort: 9093
    - name: secondary
      containerPort: 9092
    env:
    - name: KAFKA_INTER_BROKER_LISTENER_NAME
      value: "INSIDE"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: "zookeeper:2181"
    - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
      value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
    - name: KAFKA_LISTENERS
      value: "INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092"
    - name: KAFKA_ADVERTISED_LISTENERS
      value: "INSIDE://kafka:9093,OUTSIDE://localhost:9092"

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  selector:
    name: zookeeper
  ports:
    - port: 2181
      targetPort: 2181


---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: NodePort
  selector:
    name: kafka
  ports:
    - name: primary
      port: 9093
      targetPort: 9093
      nodePort: 30010     
    - name: secondary
      port: 9092
      targetPort: 9092
      nodePort: 30011