---
apiVersion: v1
kind: Pod
metadata:
  name: keycloak
  labels:
    name: keycloak
spec:
  containers:
  - name: keycloak
    image: docker.io/jboss/keycloak
    ports:
    - containerPort: 8443
    env:
    - name: DB_VENDOR
      value: postgres
    - name: DB_PASSWORD
      value: password
    - name: DB_USER
      value: testuser
    - name: DB_DATABASE
      value: "userdb"
    - name: DB_ADDR
      value: "primarydb:5432"
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_USER
      value: admin
    - name: KEYCLOAK_PASSWORD
      value: admin


---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  type: NodePort
  selector:
    name: keycloak
  ports:
    - port: 8443
      targetPort: 8443
      nodePort: 30012