---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
spec:
  containers:
  - name: mysql
    image: docker.io/mysql:latest
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
    - name: MYSQL_DATABASE
      value: primary
    - name: MYSQL_USER
      value: sa
    - name: MYSQL_PASSWORD
      value: password

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  selector:
    name: mysql
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 30003