---
apiVersion: v1
kind: Pod
metadata:
  name: primary
  labels:
    name: primary
spec:
  containers:
  - name: primary
    image: docker.io/crunchydata/crunchy-postgres:centos7-12.1-4.2.1
    ports:
    - containerPort: 5432
    env:
    - name: PGHOST
      value: /tmp
    - name: PG_ROOT_PASSWORD
      value: password
    - name: PG_PRIMARY_PASSWORD
      value: password
    - name: PG_PRIMARY_PORT
      value: "5432"
    - name: PG_PRIMARY_USER
      value: primaryuser
    - name: PG_DATABASE
      value: userdb
    - name: PG_USER
      value: testuser
    - name: PG_PASSWORD
      value: password
    - name: PG_MODE
      value: primary
    - name: MAX_CONNECTIONS
      value: "800"


---
apiVersion: v1
kind: Service
metadata:
  name: primary
spec:
  type: NodePort
  selector:
    name: primary
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30001

---
apiVersion: v1
kind: Service
metadata:
  name: primarydb
spec:
  selector:
    name: primary
  ports:
    - port: 5432
      targetPort: 5432