---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
data:
  id_rsa.pub: >-
    c3NoLWVkMjU1MTkgQUFBQUMzTnphQzFsWkRJMU5URTVBQUFBSUdzYUlxV0RvN1duczd5L01wSzZsS1ZXK1JyNFV2bjI1QlZiMUlXOHY2WWEgc3VwcG9ydEBkYXRhdHJ1Y2tlci5pbw==
type: Opaque


---
apiVersion: v1
kind: Pod
metadata:
  name: sftp-private
  labels:
    name: sftp-private
spec:
  containers:
  - name: sftp-private
    image: docker.io/atmoz/sftp
    ports:
    - containerPort: 22
    args:
    - foo::1001:0:/home/foo/upload
    volumeMounts:
    - mountPath: "/home/foo/.ssh/keys/"
      name: ssh-key
      readOnly: true
  volumes:  
  - name: ssh-key
    secret:
      secretName: ssh-key
---
apiVersion: v1
kind: Service
metadata:
  name: sftp-private
spec:
  type: NodePort
  selector:
    name: sftp-private
  ports:
    - port: 22
      targetPort: 22
      nodePort: 30007