env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
rules: {
    "prefer-destructuring": ["error", {"object": false, "array": false}],
    "no-shadow": [2, {"allow": ["done"]}],
    "max-len" : ["warn", { "code": 250 }],
    "indent": ["error", 6],
    comma-dangle: ["error", "never"],
    object-curly-spacing: ["error", "never"]
}
