FROM node:20-bookworm

LABEL "datatrucker"="api"

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 make g++ \
    && rm -rf /var/lib/apt/lists/*

COPY ./app .
RUN corepack enable && yarn install --ignore-scripts && \
    npm install -g knex && \
    npm config set strict-ssl false && \
    chgrp -R 0 /usr/src/app && \
    chmod -R g=u /usr/src/app

EXPOSE 8080
ENTRYPOINT ["npm","run"]
CMD [ "start" ]