FROM node:lts

LABEL "datatrucker"="api"

WORKDIR /usr/src/app

COPY ./app .
RUN npm install && \
    npm install -g knex && \
    npm config set strict-ssl false && \
    chgrp -R 0 /usr/src/app && \
    chmod -R g=u /usr/src/app

EXPOSE 8080
ENTRYPOINT ["npm","run"]
CMD [ "start" ]