name: DataTrucker.IO env build

on:
  push:
    branches:
    - develop
  workflow_dispatch:
  
jobs:
  initiate-testing:
    name: initiate-testing
    runs-on: ubuntu-18.04

         
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: docker/login-action@v1 
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERUSER  }}
          password: ${{ secrets.DOCKERPASS }}

      - name: provide execute permissions 
        run: chmod +x ./ci/docker-setup.sh


      - name: bring up containers
        run: ./ci/docker-setup.sh