name: DataTrucker.IO env build

on:
  push:
    branches:
    - develop
  workflow_dispatch:
  
jobs:
  initiate-testing:
    name: Wait for services to come up and the run migrate
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm install    
      - run: npm audit
