name: DataTrucker.IO env build

on:
  push:
    branches:
    - develop
  workflow_dispatch:
  
jobs:
  initiate-testing:
    name: Wait for services to come up and the run migrate
    runs-on: ubuntu-18.04
    strategy:
     matrix:
      app: [datatrucker_api,datatrucker_ui]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        run: cd ${{matrix.app}}/app ; yarn install    
      - name: Audit Dependencies
        run: cd ${{matrix.app}}/app ; yarn audit
